core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}

elasticsearch:
  hosts: ${ELASTIC_SEARCH_DATA_NODES_HOSTS:"http://localhost:9200"}
  request.timeout: ${ELASTIC_SEARCH_REQUEST_TIMEOUT:6000}
  cases.index.name.pattern: ${ELASTIC_SEARCH_CASES_INDEX_NAME_PATTERN:%s_cases}
  global.search.index.name: ${GLOBAL_SEARCH_INDEX_NAME:global_search}

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
    username: ${IDAM_CASE_DISPOSER_SYSTEM_USER_USERNAME:case.disposer.idam.system.user@gmail.com}
    password: ${IDAM_CASE_DISPOSER_SYSTEM_USER_PASSWORD:Pa55word11}
  s2s-auth:
    name: ccd_case_disposer
    url: ${IDAM_S2S_URL:http://localhost:4502}
    secret: ${IDAM_KEY_CCD_CASE_DISPOSER:AAAAAAAAAAAAAAAA}
  client:
    id: ccd-case-disposer
    secret: ${IDAM_CASE_DISPOSER_CLIENT_SECRET:idam-case-disposer-client-secret}
    redirect_uri: http://ccd-case-disposer/oauth2redirect

ccd-data:
  name: ccd_data
  secret: ${IDAM_KEY_CCD_DATA_STORE:AAAAAAAAAAAAAAAB}

ccd.case-definition.host: ${DEFINITION_STORE_HOST:http://localhost:4451}
ccd.document.store.host: ${DOCUMENT_STORE_HOST:http://localhost:4506}
ccd.role.assignment.host: ${ROLE_ASSIGNMENT_HOST:http://localhost:4096}

create.global.search: ${CREATE_GLOBAL_SEARCH:false}

app.insights.log.size: ${CASE_DISPOSER_SUMMARY_LOG_SIZE:250}
