spring:
  datasource:
    url: jdbc:postgresql://${DATA_STORE_DB_HOST:localhost}:${DATA_STORE_DB_PORT:5055}/${DATA_STORE_DB_NAME:ccd_data}${DATA_STORE_DB_OPTIONS:?stringtype=unspecified}
    username: ${DATA_STORE_DB_USERNAME:ccd}
    password: ${DATA_STORE_DB_PASSWORD:ccd}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: ${DATA_STORE_DB_CONNECTION_TIMEOUT:40000}
      idle-timeout: ${DATA_STORE_DB_IDLE_TIMEOUT:300000}
      minimum-idle: ${DATA_STORE_DB_MIN_IDLE:2}
      maximum-pool-size: ${DATA_STORE_DB_MAX_POOL_SIZE:4}

elasticsearch:
  hosts: ${ELASTIC_SEARCH_DATA_NODES_HOSTS:"http://localhost:9200"}
  request.timeout: ${ELASTIC_SEARCH_REQUEST_TIMEOUT:6000}
  cases.index.name.pattern: ${ELASTIC_SEARCH_CASES_INDEX_NAME_PATTERN:%s_cases}
  global.search.index.name: ${GLOBAL_SEARCH_INDEX_NAME:global_search}

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
    username: ${IDAM_CASE_DISPOSER_SYSTEM_USER_USERNAME:case.disposer.idam.system.user@gmail.com}
    password: ${IDAM_CASE_DISPOSER_SYSTEM_USER_PASSWORD:Pa55word11}
  s2s-auth:
    name: ccd_case_disposer
    url: ${IDAM_S2S_URL:http://localhost:4502}
    secret: ${IDAM_KEY_CCD_CASE_DISPOSER:AAAAAAAAAAAAAAAA}
  client:
    id: ccd-case-disposer
    secret: ${IDAM_CASE_DISPOSER_CLIENT_SECRET:idam-case-disposer-client-secret}
    redirect_uri: http://ccd-case-disposer/oauth2redirect

ccd-data:
  name: ccd_data
  secret: ${IDAM_KEY_CCD_DATA_STORE:AAAAAAAAAAAAAAAB}

remote:
  case-definition.host: ${DEFINITION_STORE_HOST:http://localhost:4451}
  document.store.host: ${DOCUMENT_STORE_HOST:http://localhost:4506}
  role.assignment.host: ${ROLE_ASSIGNMENT_HOST:http://localhost:4096}
  tasks.host: ${TASKS_HOST:http://localhost:4000}
  hearing.host: ${HEARING_RECORDING_HOST:http://localhost:4678}
  case.type: DPR_FT_HearingCaseType

create.global.search: ${CREATE_GLOBAL_SEARCH:true}

app.insights.log.size: ${CASE_DISPOSER_SUMMARY_LOG_SIZE:250}

thread:
  max_pool_size: ${THREAD_MAX_POOL_SIZE:10}
  core_pool_size: ${THREAD_CORE_POOL_SIZE:5}
  queue_capacity: ${THREAD_QUEUE_CAPACITY:200}
