spring:

datasource:
  ccd:
    jdbcUrl: jdbc:postgresql://${DATA_STORE_DB_HOST:localhost}:${DATA_STORE_DB_PORT:5055}/${DATA_STORE_DB_NAME:ccd_data}${DATA_STORE_DB_OPTIONS:?stringtype=unspecified}
    username: ${DATA_STORE_DB_USERNAME:ccd}
    password: ${DATA_STORE_DB_PASSWORD:ccd}
  evidence:
    jdbcUrl: jdbc:postgresql://${DATA_STORE_DB_HOST:localhost}:${DATA_STORE_DB_PORT:5055}/evidence${DATA_STORE_DB_OPTIONS:?stringtype=unspecified}
    username: ${DATA_STORE_DB_USERNAME:ccd}
    password: ${DATA_STORE_DB_PASSWORD:ccd}

elasticsearch:
  hosts: ${ELASTICSEARCH_DATA_NODES_HOSTS:"http://localhost:9200"}
  request.timeout: ${ELASTICSEARCH_REQUEST_TIMEOUT:6000}
  cases.index.name.pattern: ${ELASTICSEARCH_CASES_INDEX_NAME_PATTERN:%s_cases}
  global.search.index.name: ${GLOBAL_SEARCH_INDEX_NAME:global_search}
  global.search.index.enabled: ${GLOBAL_SEARCH_ENABLED:true}

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
    username: ${IDAM_CASE_DISPOSER_SYSTEM_USER_USERNAME:case.disposer.idam.system.user@gmail.com}
    password: ${IDAM_CASE_DISPOSER_SYSTEM_USER_PASSWORD:Pa55word11}
  s2s-auth:
    name: ccd_case_disposer
    url: ${IDAM_S2S_URL:http://localhost:4502}
    secret: ${IDAM_KEY_CCD_CASE_DISPOSER:AAAAAAAAAAAAAAAA}
  client:
    id: ccd-case-disposer
    secret: ${IDAM_CASE_DISPOSER_CLIENT_SECRET:idam-case-disposer-client-secret}
    redirect_uri: http://ccd-case-disposer/oauth2redirect

ccd.case-definition.host: ${DEFINITION_STORE_HOST:http://localhost:4451}

dm.remote.documents-delete-url: ${DM_REMOTE_DOCS_DELETE_URL:http://localhost:4506/documents/delete}
