spring:
  main:
    web-application-type: none
  config:
    import: "optional:configtree:/mnt/secrets/ccd/"
  application:
    name: Case Disposer
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DATA_STORE_DB_HOST:localhost}:${DATA_STORE_DB_PORT:5055}/${DATA_STORE_DB_NAME:ccd_data}${DATA_STORE_DB_OPTIONS:?stringtype=unspecified}
    username: ${DATA_STORE_DB_USERNAME:ccd}
    password: ${DATA_STORE_DB_PASSWORD:ccd}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: ${DATA_STORE_DB_CONNECTION_TIMEOUT:40000}
      idle-timeout: ${DATA_STORE_DB_IDLE_TIMEOUT:300000}
      minimum-idle: ${DATA_STORE_DB_MIN_IDLE:8}
      maximum-pool-size: ${DATA_STORE_DB_MAX_POOL_SIZE:20}
  flyway:
    enabled: false

elasticsearch:
  hosts: ${ELASTIC_SEARCH_DATA_NODES_HOSTS:"http://localhost:9200"}
  request.timeout: ${ELASTICSEARCH_REQUEST_TIMEOUT:6000}
  global.search:
    index.name: ${GLOBAL_SEARCH_INDEX_NAME:global_search}
  cases.index:
    type: ${ELASTICSEARCH_CASE_INDEX_TYPE:_doc}
    name.pattern: ${ELASTICSEARCH_CASES_INDEX_NAME_PATTERN:%s_cases}


deletable.case.types: ${DELETE_CASE_TYPES:}
simulated.case.types: ${SIMULATED_CASE_TYPES:}

request.limit: ${CCD_DISPOSER_REQUEST_LIMIT:1000}

remote:
  document.store:
    host: ${DOCUMENT_STORE_HOST:http://localhost:4506}
  role.assignment:
    host: ${ROLE_ASSIGNMENT_HOST:http://localhost:4096}
  log.and.audit:
    host: ${LOG_AND_AUDIT_HOST:http://localhost:4550}
  tasks:
    host: ${TASKS_HOST:http://localhost:4000}
  hearing:
    host: ${HEARING_RECORDING_HOST:http://localhost:4000}
    case.type: HearingRecordings

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
    username: ${IDAM_CASE_DISPOSER_SYSTEM_USER_USERNAME:case.disposer.idam.system.user@gmail.com}
    password: ${IDAM_CASE_DISPOSER_SYSTEM_USER_PASSWORD:Pa55word11}
  s2s-auth:
    name: ${IDAM_S2S_NAME:ccd_case_disposer}
    url: ${IDAM_S2S_URL:http://localhost:4502}
    secret: ${IDAM_KEY_CCD_CASE_DISPOSER:AAAAAAAAAAAAAAAA}
  client:
    id: ${IDAM_CASE_DISPOSER_CLIENT_ID:ccd-case-disposer}
    secret: ${IDAM_CASE_DISPOSER_CLIENT_SECRET:idam-case-disposer-client-secret}
    redirect_uri: ${IDAM_CASE_DISPOSER_CLIENT_REDIRECT_URL:http://ccd-case-disposer/oauth2redirect}

#application-insights:
#  default:
#    modules:
#      WebSyntheticRequestTelemetryInitializer:
#        enabled: false
#
#azure:
#  application-insights:
#    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:00000000-0000-0000-0000-000000000000}

smoke.test.enabled: false

app.insights.log.size: ${CASE_DISPOSER_SUMMARY_LOG_SIZE:250}

thread:
  max_pool_size: ${THREAD_MAX_POOL_SIZE:10}
  core_pool_size: ${THREAD_CORE_POOL_SIZE:5}
  queue_capacity: ${THREAD_QUEUE_CAPACITY:200}
