spring:
  config:
    import: "optional:configtree:/mnt/secrets/ccd/"
  application:
    name: Case Disposer
  main:
    web-application-type: none
  jpa:
    database: postgresql
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://${DATA_STORE_DB_HOST:localhost}:${DATA_STORE_DB_PORT:5055}/${DATA_STORE_DB_NAME:ccd_data}${DATA_STORE_DB_OPTIONS:?stringtype=unspecified}
    username: ${DATA_STORE_DB_USERNAME:ccd}
    password: ${DATA_STORE_DB_PASSWORD:ccd}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: ${DATA_STORE_DB_CONNECTION_TIMEOUT:40000}
      idle-timeout: ${DATA_STORE_DB_IDLE_TIMEOUT:300000}
      minimum-idle: ${DATA_STORE_DB_MIN_IDLE:8}
      maximum-pool-size: ${DATA_STORE_DB_MAX_POOL_SIZE:1}
  flyway:
    enabled: false

elasticsearch:
  hosts: ${ELASTICSEARCH_DATA_NODES_HOSTS:"http://localhost:9200"}
  request.timeout: ${ELASTICSEARCH_REQUEST_TIMEOUT:6000}
  global.search:
    index.name: ${GLOBAL_SEARCH_INDEX_NAME:global_search}
  cases.index:
    type: ${ELASTICSEARCH_CASE_INDEX_TYPE:_doc}
    name.pattern: ${ELASTICSEARCH_CASES_INDEX_NAME_PATTERN:%s_cases}


deletable.case.types: ${DELETE_CASE_TYPES:}
simulated.case.types: ${SIMULATED_CASE_TYPES:}

ccd.document.store.host: ${DOCUMENT_STORE_HOST:http://localhost:4506}
ccd.role.assignment.host: ${ROLE_ASSIGNMENT_HOST:http://localhost:4096}

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
    username: ${IDAM_CASE_DISPOSER_SYSTEM_USER_USERNAME:case.disposer.idam.system.user@gmail.com}
    password: ${IDAM_CASE_DISPOSER_SYSTEM_USER_PASSWORD:Pa55word11}
  s2s-auth:
    name: ccd_case_disposer
    url: ${S2S_URL:http://localhost:4502}
    secret: ${CCD_CASE_DISPOSER_IDAM_KEY:AAAAAAAAAAAAAAAA}
  client:
    id: ccd-case-disposer
    secret: ${IDAM_CASE_DISPOSER_CLIENT_SECRET:idam-case-disposer-client-secret}
    redirect_uri: http://ccd-case-disposer/oauth2redirect

azure:
  application-insights:
    web.enabled: false
    instrumentation-key: ${ccd.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

smoke.test.enabled: false
