spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:15:///localhost?stringtype=unspecified
  flyway:
    locations: classpath:db/migration
    enabled: true
    out-of-order: true
    ignore-missing-migrations: true
    baseline-version: 0001

flyway:
  noop:
    strategy: "false"

logging:
  level:
    root: ERROR
    com.zaxxer: DEBUG
    org.springframework: INFO

elasticsearch:
  hosts: ${ELASTIC_SEARCH_DATA_NODES_HOSTS:"http://localhost:4578"}
  global.search.index.name: ${GLOBAL_SEARCH_INDEX_NAME:global_search}

deletable.case.types: "deletable_case_type,bbb,ccc"
simulated.case.types: "deletable_case_type_simulation,ttt,yyy"

request.limit: ${CCD_DISPOSER_REQUEST_LIMIT:10}

idam:
  api:
    url: http://localhost:4603
    username: ${IDAM_CASE_DISPOSER_SYSTEM_USER_USERNAME:case.disposer.idam.system.user@gmail.com}
    password: ${IDAM_CASE_DISPOSER_SYSTEM_USER_PASSWORD:}
  s2s-auth:
    name: ccd_case_disposer
    url: http://localhost:4603
    secret: AAAAAAAAAAAAAAAA
  client:
    id: ccd-case-disposer
    secret: idam-case-disposer-client-secret
    redirect_uri: http://ccd-case-disposer/oauth2redirect

application-insights:
  default:
    modules:
      WebSyntheticRequestTelemetryInitializer:
        enabled: false

azure:
  application-insights:
    instrumentation-key: appinsights_key

remote:
  delayOnError: 1
  document.store:
    host: http://localhost:4603
  role.assignment:
    host: http://localhost:4603
  log.and.audit:
    host: http://localhost:4603
  tasks:
    enabled: true
    host: http://localhost:4603
  hearing:
    host: http://localhost:4603
    case.type: HearingRecordings

app.insights.log.size: 250

thread:
  max_pool_size: ${THREAD_MAX_POOL_SIZE:10}
  core_pool_size: ${THREAD_CORE_POOL_SIZE:5}
  queue_capacity: ${THREAD_QUEUE_CAPACITY:200}
