app-insights:
  dev-mode: off

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:11:///databasename?stringtype=unspecified

logging:
  level:
    root: ERROR
    com.zaxxer: DEBUG
    org.springframework: INFO

deletable.case.types: ${DELETE_CASE_TYPES:"aaa,bbb,ccc"}
