app-insights:
  dev-mode: off

spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:11:///localhost?stringtype=unspecified
  flyway:
    locations: classpath:db/migration
    enabled: true

flyway:
  noop:
    strategy: "false"

logging:
  level:
    root: ERROR
    com.zaxxer: DEBUG
    org.springframework: INFO

elasticsearch:
  hosts: ${ELASTICSEARCH_DATA_NODES_HOSTS:"http://localhost:4578"}
  global.search.index.name: ${GLOBAL_SEARCH_INDEX_NAME:global_search}

deletable.case.types: ${DELETE_CASE_TYPES:"deletable_case_type,bbb,ccc"}
simulated.case.types: ${SIMULATED_CASE_TYPES:"deletable_case_type_simulation,ttt,yyy"}

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:4603}
    username: ${IDAM_CASE_DISPOSER_SYSTEM_USER_USERNAME:case.disposer.idam.system.user@gmail.com}
    password: ${IDAM_CASE_DISPOSER_SYSTEM_USER_PASSWORD:Pa55word11}
  s2s-auth:
    name: ccd_case_disposer
    url: ${S2S_URL:http://localhost:4603}
    secret: ${CCD_CASE_DISPOSER_IDAM_KEY:AAAAAAAAAAAAAAAA}

ccd.document.store.host: ${DOCUMENT_STORE_HOST:http://localhost:4603}
ccd.role.assignment.host: ${ROLE_ASSIGNMENT_HOST:http://localhost:4603}
