spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:11:///localhost?stringtype=unspecified
  flyway:
    locations: classpath:db/migration
    enabled: true
    out-ofrder: true
    ignore-missing-migrations: true
    baseline-version: 0001

flyway:
  noop:
    strategy: "false"

logging:
  level:
    root: ERROR
    com.zaxxer: DEBUG
    org.springframework: INFO

elasticsearch:
  hosts: ${ELASTIC_SEARCH_DATA_NODES_HOSTS:"http://localhost:4578"}
  global.search.index.name: ${GLOBAL_SEARCH_INDEX_NAME:global_search}

deletable.case.types: ${DELETE_CASE_TYPES:"deletable_case_type,bbb,ccc"}
simulated.case.types: ${SIMULATED_CASE_TYPES:"deletable_case_type_simulation,ttt,yyy"}

idam:
  api:
    url: http://localhost:4603
    username: ${IDAM_CASE_DISPOSER_SYSTEM_USER_USERNAME:case.disposer.idam.system.user@gmail.com}
    password: ${IDAM_CASE_DISPOSER_SYSTEM_USER_PASSWORD:Pa55word11}
  s2s-auth:
    name: ccd_case_disposer
    url: http://localhost:4603
    secret: AAAAAAAAAAAAAAAA
  client:
    id: ccd-case-disposer
    secret: idam-case-disposer-client-secret
    redirect_uri: http://ccd-case-disposer/oauth2redirect

application-insights:
  default:
    modules:
      WebSyntheticRequestTelemetryInitializer:
        enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:"Test"}

ccd.document.store.host: http://localhost:4603
ccd.role.assignment.host: http://localhost:4603

app.insights.log.size: 250
